CREATE TABLE IF NOT EXISTS marketing_campaigns (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    start_date TEXT,
    end_date TEXT,
    goal TEXT,
    progress INTEGER DEFAULT 0,
    metric TEXT,
    type TEXT,
    prize TEXT,
    ticket_price REAL,
    winner_id TEXT,
    participants JSON DEFAULT '[]',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Seed TV Raffle Data
INSERT INTO marketing_campaigns (id, name, status, start_date, end_date, goal, progress, metric, type, prize, ticket_price, winner_id, participants)
VALUES (
    'camp-tv-raffle',
    '65" Samsung Smart TV Raffle',
    'completed',
    '2025-12-01',
    '2025-12-11',
    '150 Entries',
    100,
    'entries',
    'raffle',
    '65" Samsung Smart TV',
    10,
    'p-57',
    '[
      {"id": "p-1", "ticketNumber": 1, "name": "Elizabeth Elliot", "contact": "elizabeth@example.com", "paid": true, "date": "1/18/26", "paymentMethod": "Card", "amount": "$10", "comments": ""},
      {"id": "p-2", "ticketNumber": 2, "name": "Kim Bolander", "contact": "----", "paid": true, "date": "", "paymentMethod": "", "amount": "$10", "comments": ""},
      {"id": "p-3", "ticketNumber": 3, "name": "Amy Kelly", "contact": "----", "paid": true, "date": "", "paymentMethod": "", "amount": "$10", "comments": ""},
      {"id": "p-4", "ticketNumber": 4, "name": "Leti Luna", "contact": "----", "paid": true, "date": "", "paymentMethod": "", "amount": "$10", "comments": ""},
      {"id": "p-5", "ticketNumber": 5, "name": "Danielle Padilla", "contact": "----", "paid": true, "date": "", "paymentMethod": "", "amount": "$10", "comments": ""},
      {"id": "p-6", "ticketNumber": 6, "name": "Marci Baver", "contact": "----", "paid": true, "date": "", "paymentMethod": "", "amount": "$10", "comments": ""},
      {"id": "p-7", "ticketNumber": 7, "name": "Andrea Gladson", "contact": "----", "paid": true, "date": "", "paymentMethod": "", "amount": "$10", "comments": ""},
      {"id": "p-8", "ticketNumber": 8, "name": "Franciso Alvarado", "contact": "----", "paid": true, "date": "", "paymentMethod": "", "amount": "$10", "comments": ""},
      {"id": "p-9", "ticketNumber": 9, "name": "Lynn Berry", "contact": "----", "paid": true, "date": "", "paymentMethod": "", "amount": "$10", "comments": ""},
      {"id": "p-10", "ticketNumber": 10, "name": "Jenna Bell", "contact": "----", "paid": true, "date": "", "paymentMethod": "", "amount": "$10", "comments": ""},
      {"id": "p-11", "ticketNumber": 11, "name": "Eva King", "contact": "----", "paid": true, "date": "", "paymentMethod": "", "amount": "$10", "comments": ""},
      {"id": "p-12", "ticketNumber": 12, "name": "Tammy Martin", "contact": "----", "paid": true, "date": "", "paymentMethod": "", "amount": "$10", "comments": ""},
      {"id": "p-13", "ticketNumber": 13, "name": "Kim Bolander", "contact": "----", "paid": true, "date": "", "paymentMethod": "", "amount": "$10", "comments": ""},
      {"id": "p-14", "ticketNumber": 14, "name": "Elizabeth Elliot", "contact": "----", "paid": true, "date": "", "paymentMethod": "", "amount": "$10", "comments": ""},
      {"id": "p-15", "ticketNumber": 15, "name": "Andrea Gladson", "contact": "----", "paid": true, "date": "", "paymentMethod": "", "amount": "$10", "comments": ""},
      {"id": "p-16", "ticketNumber": 16, "name": "Kristyn Vargas", "contact": "----", "paid": true, "date": "", "paymentMethod": "", "amount": "$10", "comments": ""},
      {"id": "p-17", "ticketNumber": 17, "name": "Wendy Kolber", "contact": "----", "paid": true, "date": "", "paymentMethod": "", "amount": "$10", "comments": ""},
      {"id": "p-18", "ticketNumber": 18, "name": "Lynn Berry", "contact": "----", "paid": true, "date": "", "paymentMethod": "", "amount": "$10", "comments": ""},
      {"id": "p-19", "ticketNumber": 19, "name": "Kim Bolander", "contact": "----", "paid": true, "date": "", "paymentMethod": "", "amount": "$10", "comments": ""},
      {"id": "p-20", "ticketNumber": 20, "name": "Yesenia Castilo", "contact": "323-382-5659", "paid": true, "date": "1/10/26", "paymentMethod": "Cash", "amount": "$10", "comments": ""},
      {"id": "p-21", "ticketNumber": 21, "name": "Eva King", "contact": "----", "paid": true, "date": "", "paymentMethod": "", "amount": "$10", "comments": ""},
      {"id": "p-22", "ticketNumber": 22, "name": "Ivette AV", "contact": "----", "paid": true, "date": "", "paymentMethod": "", "amount": "$10", "comments": ""},
      {"id": "p-23", "ticketNumber": 23, "name": "Danielle Padilla", "contact": "----", "paid": true, "date": "", "paymentMethod": "", "amount": "$10", "comments": ""},
      {"id": "p-24", "ticketNumber": 24, "name": "Tammy Martin", "contact": "----", "paid": true, "date": "", "paymentMethod": "", "amount": "$10", "comments": ""},
      {"id": "p-25", "ticketNumber": 25, "name": "Steve SkyTurtle", "contact": "----", "paid": true, "date": "", "paymentMethod": "", "amount": "$10", "comments": ""},
      {"id": "p-26", "ticketNumber": 26, "name": "Wendy Kolber", "contact": "----", "paid": true, "date": "", "paymentMethod": "", "amount": "$10", "comments": ""},
      {"id": "p-27", "ticketNumber": 27, "name": "Andrea Gladson", "contact": "----", "paid": true, "date": "", "paymentMethod": "", "amount": "$10", "comments": ""},
      {"id": "p-28", "ticketNumber": 28, "name": "Wendy Kolber", "contact": "----", "paid": true, "date": "", "paymentMethod": "", "amount": "$10", "comments": ""},
      {"id": "p-29", "ticketNumber": 29, "name": "Lia Shaw", "contact": "626-314-0721", "paid": true, "date": "1/18/26", "paymentMethod": "Cash", "amount": "$10", "comments": ""}
    ]'
);
