export const settingsCategories = [
  {
    id: 'general',
    label: 'General',
    icon: 'cog',
    description: 'Organization profile, notifications, system status.',
    color: '#64748b',
  },
  {
    id: 'user',
    label: 'User Settings',
    icon: 'user',
    description: 'Manage your personal profile and preferences.',
    color: '#3b82f6',
  },
  {
    id: 'website',
    label: 'Website',
    icon: 'globe',
    description: 'Manage public facing application forms and email routing.',
    color: '#8b5cf6',
  },
  {
    id: 'overview',
    label: 'Overview',
    icon: 'dashboard',
    description: 'Dashboard widgets and visibility settings.',
    color: '#06b6d4',
  },
  {
    id: 'volunteers',
    label: 'Volunteers',
    icon: 'users',
    description: 'Gamification, shift rules, and application settings.',
    color: '#f97316',
  },
  {
    id: 'calendar',
    label: 'Calendar',
    icon: 'calendar',
    description: 'Scheduling preferences.',
    color: '#ef4444',
  },
  {
    id: 'pets',
    label: 'Pet Records',
    icon: 'pawPrint',
    description: 'Default intake fields and species.',
    color: '#eab308',
    viewBox: '0 0 128 128',
  },
  {
    id: 'health',
    label: 'Medical',
    icon: 'activity',
    description: 'Vaccine protocols and vet contacts.',
    color: '#ef4444',
  },
  {
    id: 'transport',
    label: 'Transport',
    icon: 'truck',
    description: 'Vehicle fleet and driver requirements.',
    color: '#10b981',
  },
  {
    id: 'timesheets',
    label: 'Timesheets',
    icon: 'clock',
    description: 'Clock-in/out rules and roundings.',
    color: '#6366f1',
  },
  {
    id: 'messages',
    label: 'Messages',
    icon: 'mail',
    description: 'Auto-replies and signature settings.',
    color: '#f43f5e',
  },
  {
    id: 'donations',
    label: 'Donations',
    icon: 'donate',
    description: 'Payment gateways and receipt templates.',
    color: '#22c55e',
  },
  {
    id: 'inventory',
    label: 'Inventory',
    icon: 'box',
    description: 'Low stock alerts and categories.',
    color: '#a855f7',
  },
  {
    id: 'marketing',
    label: 'Marketing',
    icon: 'megaphone',
    description: 'Social media integrations and branding.',
    color: '#db2777',
  },
  {
    id: 'kiosk',
    label: 'Intake Kiosk',
    icon: 'monitor',
    description: 'Kiosk display and timeout settings.',
    color: '#f59e0b',
  },
  {
    id: 'kennel',
    label: 'Smart Kennel Cards',
    icon: 'tag',
    description: 'Digital cage card layouts.',
    color: '#14b8a6',
  },
  {
    id: 'events',
    label: 'Event Signage',
    icon: 'sign',
    description: 'Digital signage playlist management.',
    color: '#f472b6',
  },
]
