package main

import (
	"context"
	"time"

	"github.com/cconner57/adoption-os/backend/internal/data"
	"github.com/lib/pq"
)

func (app *application) seedVolunteers() {
	volunteers := []data.Volunteer{
		{
			FirstName:             "Linda",
			LastName:              "Taira",
			Email:                 "linda.taira@example.com",
			Phone:                 "555-0201",
			Status:                "active",
			Role:                  "Tier 2",
			JoinDate:              "2022-03-15",
			Bio:                   "Dedicated volunteer with a passion for senior dogs.",
			Skills:                []string{"Cat Behavior Training", "Medication Administration"},
			ReliabilityScore:      100,
			Address:               "101 Pine St",
			City:                  "Springfield",
			Zip:                   "90210",
			Birthday:              "1985-04-12",
			Allergies:             false,
			EmergencyContactName:  "John Taira",
			EmergencyContactPhone: "555-1201",
			InterestReason:        "Love helping animals in need.",
			PositionPreferences:   []string{"Feeding/Cleaning", "Cat Socializing"},
			Availability:          []string{"10AM – 12PM", "2PM – 4PM"},
			TotalHours:            320,
			Streak:                24,
			Badges:                []string{"New Recruit", "Rookie", "Regular", "Veteran", "10 Hours", "50 Hours", "Bronze Service", "Silver Service", "Gold Service", "Poop Scoop Pro"},
		},
		{
			FirstName:             "Chris",
			LastName:              "Conner",
			Email:                 "chris.conner@example.com",
			Phone:                 "555-0202",
			Status:                "active",
			Role:                  "Tier 2",
			JoinDate:              "2021-11-10",
			Bio:                   "Loves organizing the shelter storage and walking the big dogs.",
			Skills:                []string{"Logistics", "Feeding/Cleaning"},
			ReliabilityScore:      96,
			Address:               "202 Oak Ave",
			City:                  "Springfield",
			Zip:                   "90210",
			Birthday:              "1990-07-22",
			Allergies:             true,
			EmergencyContactName:  "Sarah Conner",
			EmergencyContactPhone: "555-1202",
			InterestReason:        "Want to support the local shelter.",
			PositionPreferences:   []string{"Feeding/Cleaning", "Customer Support"},
			Availability:          []string{"4PM – 6PM"},
			TotalHours:            410,
			Streak:                8,
			Badges:                []string{"Veteran", "Platinum Service", "Weekend Warrior"},
		},
		{
			FirstName:             "Allison",
			LastName:              "Bruins",
			Email:                 "allison.b@example.com",
			Phone:                 "555-0203",
			Status:                "active",
			Role:                  "Tier 2",
			JoinDate:              "2023-01-05",
			Bio:                   "Cat expert and foster parent.",
			Skills:                []string{"Cat Socializing", "Photography"},
			ReliabilityScore:      98,
			Address:               "303 Maple Dr",
			City:                  "Springfield",
			Zip:                   "90210",
			Birthday:              "1992-02-28",
			Allergies:             false,
			EmergencyContactName:  "Mike Bruins",
			EmergencyContactPhone: "555-1203",
			InterestReason:        "Huge cat lover.",
			PositionPreferences:   []string{"Cat Socializing"},
			Availability:          []string{"6PM – 8PM", "Adoption Event: 12pm - 2pm"},
			TotalHours:            180,
			Streak:                15,
			Badges:                []string{"Cat Whisperer", "Silver Service", "Matchmaker"},
		},
		{
			FirstName:             "Katelyn",
			LastName:              "Johnson",
			Email:                 "katelyn.j@example.com",
			Phone:                 "555-0301",
			Status:                "active",
			Role:                  "Tier 1",
			JoinDate:              "2023-06-15",
			Bio:                   "New to the area, looking to make friends and help pets.",
			Skills:                []string{"Feeding/Cleaning"},
			ReliabilityScore:      92,
			Address:               "404 Elm St",
			City:                  "Springfield",
			Zip:                   "90210",
			Birthday:              "1998-09-10",
			Allergies:             false,
			EmergencyContactName:  "Mom",
			EmergencyContactPhone: "555-1301",
			InterestReason:        "Community service.",
			PositionPreferences:   []string{"Feeding/Cleaning"},
			Availability:          []string{"10AM – 12PM"},
			TotalHours:            60,
			Streak:                4,
			Badges:                []string{"50 Hours", "Cleaning Crew"},
		},
		{
			FirstName:             "Alejandra",
			LastName:              "",
			Email:                 "alejandra@example.com",
			Phone:                 "555-0302",
			Status:                "active",
			Role:                  "Tier 1",
			JoinDate:              "2023-08-01",
			Bio:                   "Enjoys spending time with the shy cats.",
			Skills:                []string{"Cat Socializing"},
			ReliabilityScore:      88,
			Address:               "505 Cedar Ln",
			City:                  "Springfield",
			Zip:                   "90210",
			Birthday:              "2000-01-15",
			Allergies:             true,
			EmergencyContactName:  "Maria",
			EmergencyContactPhone: "555-1302",
			InterestReason:        "Love cats.",
			PositionPreferences:   []string{"Cat Socializing"},
			Availability:          []string{"2PM – 4PM"},
			TotalHours:            45,
			Streak:                2,
			Badges:                []string{"10 Hours"},
		},
		{
			FirstName:             "Arianna",
			LastName:              "Medal",
			Email:                 "arianna.m@example.com",
			Phone:                 "555-0303",
			Status:                "active",
			Role:                  "Tier 1",
			JoinDate:              "2023-07-20",
			Bio:                   "Always happy to help with laundry and dishes.",
			Skills:                []string{"Feeding/Cleaning"},
			ReliabilityScore:      95,
			Address:               "606 Birch Rd",
			City:                  "Springfield",
			Zip:                   "90210",
			Birthday:              "1996-11-30",
			Allergies:             false,
			EmergencyContactName:  "Dad",
			EmergencyContactPhone: "555-1303",
			InterestReason:        "Want to help.",
			PositionPreferences:   []string{"Feeding/Cleaning"},
			Availability:          []string{"6PM – 8PM"},
			TotalHours:            55,
			Streak:                6,
			Badges:                []string{"Laundry Lord", "50 Hours"},
		},
		{
			FirstName:             "Bella",
			LastName:              "",
			Email:                 "bella@example.com",
			Phone:                 "555-0304",
			Status:                "pending",
			Role:                  "Tier 1",
			JoinDate:              "2023-12-01",
			Bio:                   "Just finished orientation.",
			Skills:                []string{},
			ReliabilityScore:      0,
			Address:               "707 Spruce St",
			City:                  "Springfield",
			Zip:                   "90210",
			Birthday:              "2001-05-05",
			Allergies:             false,
			EmergencyContactName:  "Emergency Contact",
			EmergencyContactPhone: "555-1304",
			InterestReason:        "New volunteer.",
			PositionPreferences:   []string{"Feeding/Cleaning"},
			Availability:          []string{"Adoption Event: 12pm - 2pm", "Adoption Event: 2pm - 4pm"},
			TotalHours:            0,
			Streak:                0,
			Badges:                []string{"New Recruit"},
		},
		{
			FirstName:             "Brandon",
			LastName:              "Siou",
			Email:                 "brandon.siou@example.com",
			Phone:                 "555-0305",
			Status:                "active",
			Role:                  "Tier 1",
			JoinDate:              "2023-05-10",
			Bio:                   "Strong and willing to handle large dogs.",
			Skills:                []string{"Feeding/Cleaning", "Maintenance"},
			ReliabilityScore:      90,
			Address:               "808 Ash Ave",
			City:                  "Springfield",
			Zip:                   "90210",
			Birthday:              "1993-08-18",
			Allergies:             false,
			EmergencyContactName:  "Wife",
			EmergencyContactPhone: "555-1305",
			InterestReason:        "Exercise and cats.",
			PositionPreferences:   []string{"Feeding/Cleaning"},
			Availability:          []string{"Adoption Event: 2pm - 4pm"},
			TotalHours:            80,
			Streak:                3,
			Badges:                []string{"50 Hours", "Dog Walker"},
		},
		{
			FirstName:             "Katie",
			LastName:              "",
			Email:                 "katie@example.com",
			Phone:                 "555-0306",
			Status:                "inactive",
			Role:                  "Tier 1",
			JoinDate:              "2022-09-01",
			Bio:                   "Moved out of town temporarily.",
			Skills:                []string{"Feeding/Cleaning"},
			ReliabilityScore:      100,
			Address:               "909 Walnut St",
			City:                  "Springfield",
			Zip:                   "90210",
			Birthday:              "1999-03-22",
			Allergies:             false,
			EmergencyContactName:  "Mom",
			EmergencyContactPhone: "555-1306",
			InterestReason:        "School credit.",
			PositionPreferences:   []string{"Feeding/Cleaning"},
			Availability:          []string{},
			TotalHours:            120,
			Streak:                0,
			Badges:                []string{"Bronze Service"},
		},
		{
			FirstName:             "Leanne",
			LastName:              "",
			Email:                 "leanne@example.com",
			Phone:                 "555-0307",
			Status:                "active",
			Role:                  "Tier 1",
			JoinDate:              "2023-10-05",
			Bio:                   "Loves puppies!",
			Skills:                []string{"Cat Socializing"},
			ReliabilityScore:      85,
			Address:               "1010 Chestnut Dr",
			City:                  "Springfield",
			Zip:                   "90210",
			Birthday:              "1997-12-12",
			Allergies:             false,
			EmergencyContactName:  "Sister",
			EmergencyContactPhone: "555-1307",
			InterestReason:        "Kittens.",
			PositionPreferences:   []string{"Cat Socializing"},
			Availability:          []string{"6PM – 8PM"},
			TotalHours:            25,
			Streak:                2,
			Badges:                []string{"10 Hours", "Puppy Pal"},
		},
		{
			FirstName:             "Lindsey",
			LastName:              "",
			Email:                 "lindsey@example.com",
			Phone:                 "555-0308",
			Status:                "active",
			Role:                  "Tier 1",
			JoinDate:              "2023-04-15",
			Bio:                   "Detail oriented cleaner.",
			Skills:                []string{"Feeding/Cleaning", "Organization"},
			ReliabilityScore:      97,
			Address:               "1111 Willow Way",
			City:                  "Springfield",
			Zip:                   "90210",
			Birthday:              "1994-06-30",
			Allergies:             true,
			EmergencyContactName:  "Husband",
			EmergencyContactPhone: "555-1308",
			InterestReason:        "Order and cleanliness.",
			PositionPreferences:   []string{"Feeding/Cleaning"},
			Availability:          []string{"10AM – 12PM"},
			TotalHours:            95,
			Streak:                10,
			Badges:                []string{"Cleaning Crew", "50 Hours"},
		},
		{
			FirstName:             "Lynn",
			LastName:              "",
			Email:                 "lynn@example.com",
			Phone:                 "555-0309",
			Status:                "active",
			Role:                  "Tier 1",
			JoinDate:              "2023-02-20",
			Bio:                   "Retired teacher loves reading to cats.",
			Skills:                []string{"Cat Socializing"},
			ReliabilityScore:      100,
			Address:               "1212 Magnolia Ct",
			City:                  "Springfield",
			Zip:                   "90210",
			Birthday:              "1960-01-25",
			Allergies:             false,
			EmergencyContactName:  "Son",
			EmergencyContactPhone: "555-1309",
			InterestReason:        "Company.",
			PositionPreferences:   []string{"Cat Socialization"},
			Availability:          []string{"10AM – 12PM", "12PM – 2PM"},
			TotalHours:            300,
			Streak:                40,
			Badges:                []string{"Cat Whisperer", "Silver Service", "Reliable"},
		},
		{
			FirstName:             "Michelle",
			LastName:              "Black",
			Email:                 "michelle.b@example.com",
			Phone:                 "555-0310",
			Status:                "active",
			Role:                  "Tier 1",
			JoinDate:              "2023-09-10",
			Bio:                   "Photographer by trade.",
			Skills:                []string{"Photography", "Cat Socializing"},
			ReliabilityScore:      94,
			Address:               "1313 Palm St",
			City:                  "Springfield",
			Zip:                   "90210",
			Birthday:              "1988-10-08",
			Allergies:             false,
			EmergencyContactName:  "Partner",
			EmergencyContactPhone: "555-1310",
			InterestReason:        "Taking photos of adoptable pets.",
			PositionPreferences:   []string{"Customer Support", "Cat Socializing"},
			Availability:          []string{"Adoption Event: 2pm - 4pm"},
			TotalHours:            70,
			Streak:                5,
			Badges:                []string{"Photographer", "50 Hours"},
		},
	}

	app.logger.Info("Seeding volunteers...")

	for _, v := range volunteers {
		// Basic insert using raw query to include ID if possible or just let autoincrement
		// Since IDs in mock are strings like 't2-1', we can't use them directly in SERIAL id field easily unless we stripped 't2-'.
		// We'll let Postgres handle IDs.

		query := `
		INSERT INTO volunteers (
			first_name, last_name, email, phone, address, city, zip, role, status,
			bio, photo_url, reliability_score, total_hours, streak, join_date, allergies,
			skills, position_preferences, availability, badges,
			birthday, emergency_contact_name, emergency_contact_phone, interest_reason, volunteer_experience
		)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25)
		ON CONFLICT (email) DO NOTHING`
		// Added ON CONFLICT to avoid duplication

		args := []any{
			v.FirstName, v.LastName, v.Email, v.Phone, v.Address, v.City, v.Zip, v.Role, v.Status,
			v.Bio, v.PhotoURL, v.ReliabilityScore, v.TotalHours, v.Streak, v.JoinDate, v.Allergies,
			pq.Array(v.Skills), pq.Array(v.PositionPreferences), pq.Array(v.Availability), pq.Array(v.Badges),
			v.Birthday, v.EmergencyContactName, v.EmergencyContactPhone, v.InterestReason, v.VolunteerExperience,
		}

		ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
		defer cancel()

		_, err := app.db.ExecContext(ctx, query, args...)
		if err != nil {
			app.logger.Error("Failed to seed volunteer", "error", err)
		}
	}

	app.logger.Info("Volunteers seeded successfully")
}
