// Export all pages for easy access
export { default as About } from './About.vue'
export { default as Adopt } from './Adopt.vue'
export { default as Donate } from './Donate.vue'
export { default as Home } from './Home.vue'
export { default as Login } from './Login.vue'
export { default as NotFound } from './NotFound.vue'
export { default as PetAdoption } from './PetAdoption.vue'
export { default as SurrenderPet } from './SurrenderPet.vue'
export { default as Volunteer } from './Volunteer.vue'
export { default as Applications } from './admin/Applications.vue'
