// ... existing code ...
export interface IVolunteer {
  id: string
  firstName: string
  lastName: string
  email: string
  phone: string
  status: 'active' | 'inactive' | 'pending'
  role: 'Tier 1' | 'Tier 2' | 'Teen' | 'Admin'
  joinDate: string
  bio?: string
  photoUrl?: string
  skills: string[]
  reliabilityScore: number // 0-100

  // Detailed Form Data
  address: string
  city: string
  zip: string
  birthday: string
  age?: number
  allergies: boolean
  emergencyContactName: string
  emergencyContactPhone: string
  volunteerExperience?: string
  interestReason?: string
  positionPreferences: string[]
  availability: string[] // "Monday Morning", "Tuesday Evening"

  // Gamification Metrics
  totalHours: number
  streak: number // consecutive weeks
  badges: string[] // "Early Bird", "Weekend Warrior"
}

export interface IShift {
  id: string
  volunteerId: string
  date: string // ISO date
  startTime: string // "09:00"
  endTime: string // "13:00"
  role: string // "Dog Walking", "Cleaning", etc.
  status: 'scheduled' | 'all_good' | 'late' | 'no_show' | 'cancelled'
  notes?: string
}

export interface IIncident {
  id: string
  volunteerId: string
  date: string // ISO date
  severity: 'low' | 'medium' | 'high'
  description: string
  recordedBy: string
}

export const mockVolunteers: IVolunteer[] = [
  // Tier 2
  {
    id: 't2-1',
    firstName: 'Linda',
    lastName: 'Taira',
    email: 'linda.taira@example.com',
    phone: '555-0201',
    status: 'active',
    role: 'Tier 2',
    joinDate: '2022-03-15',
    bio: 'Dedicated volunteer with a passion for senior dogs.',
    skills: ['Dog Training', 'Medication Administration'],
    reliabilityScore: 100,
    address: '101 Pine St',
    city: 'Springfield',
    zip: '90210',
    birthday: '1985-04-12',
    allergies: false,
    emergencyContactName: 'John Taira',
    emergencyContactPhone: '555-1201',
    interestReason: 'Love helping animals in need.',
    positionPreferences: ['Dog Walking', 'Vet Checks'],
    availability: ['Monday Morning', 'Wednesday Morning'],
    totalHours: 320,
    streak: 24,
    badges: [
      'New Recruit',
      'Rookie',
      'Regular',
      'Veteran',
      '10 Hours',
      '50 Hours',
      'Bronze Service',
      'Silver Service',
      'Gold Service',
      'Poop Scoop Pro',
    ],
  },
  {
    id: 't2-2',
    firstName: 'Chris',
    lastName: 'Conner',
    email: 'chris.conner@example.com',
    phone: '555-0202',
    status: 'active',
    role: 'Tier 2',
    joinDate: '2021-11-10',
    bio: 'Loves organizing the shelter storage and walking the big dogs.',
    skills: ['Logistics', 'Dog Walking'],
    reliabilityScore: 96,
    address: '202 Oak Ave',
    city: 'Springfield',
    zip: '90210',
    birthday: '1990-07-22',
    allergies: true,
    emergencyContactName: 'Sarah Conner',
    emergencyContactPhone: '555-1202',
    interestReason: 'Want to support the local shelter.',
    positionPreferences: ['Dog Walking', 'Events'],
    availability: ['Tuesday Afternoon'],
    totalHours: 410,
    streak: 8,
    badges: ['Veteran', 'Platinum Service', 'Weekend Warrior'],
  },
  {
    id: 't2-3',
    firstName: 'Allison',
    lastName: 'Bruins',
    email: 'allison.b@example.com',
    phone: '555-0203',
    status: 'active',
    role: 'Tier 2',
    joinDate: '2023-01-05',
    bio: 'Cat expert and foster parent.',
    skills: ['Cat Socialization', 'Photography'],
    reliabilityScore: 98,
    address: '303 Maple Dr',
    city: 'Springfield',
    zip: '90210',
    birthday: '1992-02-28',
    allergies: false,
    emergencyContactName: 'Mike Bruins',
    emergencyContactPhone: '555-1203',
    interestReason: 'Huge cat lover.',
    positionPreferences: ['Cat Socialization', 'Foster'],
    availability: ['Thursday Evening', 'Saturday Morning'],
    totalHours: 180,
    streak: 15,
    badges: ['Cat Whisperer', 'Silver Service', 'Matchmaker'],
  },

  // Tier 1
  {
    id: 't1-1',
    firstName: 'Katelyn',
    lastName: 'Johnson',
    email: 'katelyn.j@example.com',
    phone: '555-0301',
    status: 'active',
    role: 'Tier 1',
    joinDate: '2023-06-15',
    bio: 'New to the area, looking to make friends and help pets.',
    skills: ['Cleaning', 'Feeding'],
    reliabilityScore: 92,
    address: '404 Elm St',
    city: 'Springfield',
    zip: '90210',
    birthday: '1998-09-10',
    allergies: false,
    emergencyContactName: 'Mom',
    emergencyContactPhone: '555-1301',
    interestReason: 'Community service.',
    positionPreferences: ['Cleaning'],
    availability: ['Sunday Morning'],
    totalHours: 60,
    streak: 4,
    badges: ['50 Hours', 'Cleaning Crew'],
  },
  {
    id: 't1-2',
    firstName: 'Alejandra',
    lastName: '',
    email: 'alejandra@example.com',
    phone: '555-0302',
    status: 'active',
    role: 'Tier 1',
    joinDate: '2023-08-01',
    bio: 'Enjoys spending time with the shy cats.',
    skills: ['Cat Socialization'],
    reliabilityScore: 88,
    address: '505 Cedar Ln',
    city: 'Springfield',
    zip: '90210',
    birthday: '2000-01-15',
    allergies: true,
    emergencyContactName: 'Maria',
    emergencyContactPhone: '555-1302',
    interestReason: 'Love cats.',
    positionPreferences: ['Cat Socialization'],
    availability: ['Friday Afternoon'],
    totalHours: 45,
    streak: 2,
    badges: ['10 Hours'],
  },
  {
    id: 't1-3',
    firstName: 'Arianna',
    lastName: 'Medal',
    email: 'arianna.m@example.com',
    phone: '555-0303',
    status: 'active',
    role: 'Tier 1',
    joinDate: '2023-07-20',
    bio: 'Always happy to help with laundry and dishes.',
    skills: ['Cleaning'],
    reliabilityScore: 95,
    address: '606 Birch Rd',
    city: 'Springfield',
    zip: '90210',
    birthday: '1996-11-30',
    allergies: false,
    emergencyContactName: 'Dad',
    emergencyContactPhone: '555-1303',
    interestReason: 'Want to help.',
    positionPreferences: ['Cleaning'],
    availability: ['Wednesday Evening'],
    totalHours: 55,
    streak: 6,
    badges: ['Laundry Lord', '50 Hours'],
  },
  {
    id: 't1-4',
    firstName: 'Bella',
    lastName: '',
    email: 'bella@example.com',
    phone: '555-0304',
    status: 'pending',
    role: 'Tier 1',
    joinDate: '2023-12-01',
    bio: 'Just finished orientation.',
    skills: [],
    reliabilityScore: 0,
    address: '707 Spruce St',
    city: 'Springfield',
    zip: '90210',
    birthday: '2001-05-05',
    allergies: false,
    emergencyContactName: 'Emergency Contact',
    emergencyContactPhone: '555-1304',
    interestReason: 'New volunteer.',
    positionPreferences: ['Dog Walking'],
    availability: ['Weekend'],
    totalHours: 0,
    streak: 0,
    badges: ['New Recruit'],
  },
  {
    id: 't1-5',
    firstName: 'Brandon',
    lastName: 'Siou',
    email: 'brandon.siou@example.com',
    phone: '555-0305',
    status: 'active',
    role: 'Tier 1',
    joinDate: '2023-05-10',
    bio: 'Strong and willing to handle large dogs.',
    skills: ['Dog Walking', 'Maintenance'],
    reliabilityScore: 90,
    address: '808 Ash Ave',
    city: 'Springfield',
    zip: '90210',
    birthday: '1993-08-18',
    allergies: false,
    emergencyContactName: 'Wife',
    emergencyContactPhone: '555-1305',
    interestReason: 'Exercise and dogs.',
    positionPreferences: ['Dog Walking'],
    availability: ['Saturday Afternoon'],
    totalHours: 80,
    streak: 3,
    badges: ['50 Hours', 'Dog Walker'],
  },
  {
    id: 't1-6',
    firstName: 'Katie',
    lastName: '',
    email: 'katie@example.com',
    phone: '555-0306',
    status: 'inactive',
    role: 'Tier 1',
    joinDate: '2022-09-01',
    bio: 'Moved out of town temporarily.',
    skills: ['Feeding'],
    reliabilityScore: 100,
    address: '909 Walnut St',
    city: 'Springfield',
    zip: '90210',
    birthday: '1999-03-22',
    allergies: false,
    emergencyContactName: 'Mom',
    emergencyContactPhone: '555-1306',
    interestReason: 'School credit.',
    positionPreferences: ['Feeding'],
    availability: [],
    totalHours: 120,
    streak: 0,
    badges: ['Bronze Service'],
  },
  {
    id: 't1-7',
    firstName: 'Leanne',
    lastName: '',
    email: 'leanne@example.com',
    phone: '555-0307',
    status: 'active',
    role: 'Tier 1',
    joinDate: '2023-10-05',
    bio: 'Loves puppies!',
    skills: ['Socialization'],
    reliabilityScore: 85,
    address: '1010 Chestnut Dr',
    city: 'Springfield',
    zip: '90210',
    birthday: '1997-12-12',
    allergies: false,
    emergencyContactName: 'Sister',
    emergencyContactPhone: '555-1307',
    interestReason: 'Puppies.',
    positionPreferences: ['Socialization'],
    availability: ['Monday Evening'],
    totalHours: 25,
    streak: 2,
    badges: ['10 Hours', 'Puppy Pal'],
  },
  {
    id: 't1-8',
    firstName: 'Lindsey',
    lastName: '',
    email: 'lindsey@example.com',
    phone: '555-0308',
    status: 'active',
    role: 'Tier 1',
    joinDate: '2023-04-15',
    bio: 'Detail oriented cleaner.',
    skills: ['Cleaning', 'Organization'],
    reliabilityScore: 97,
    address: '1111 Willow Way',
    city: 'Springfield',
    zip: '90210',
    birthday: '1994-06-30',
    allergies: true,
    emergencyContactName: 'Husband',
    emergencyContactPhone: '555-1308',
    interestReason: 'Order and cleanliness.',
    positionPreferences: ['Cleaning'],
    availability: ['Tuesday Morning'],
    totalHours: 95,
    streak: 10,
    badges: ['Cleaning Crew', '50 Hours'],
  },
  {
    id: 't1-9',
    firstName: 'Lynn',
    lastName: '',
    email: 'lynn@example.com',
    phone: '555-0309',
    status: 'active',
    role: 'Tier 1',
    joinDate: '2023-02-20',
    bio: 'Retired teacher loves reading to cats.',
    skills: ['Cat Socialization'],
    reliabilityScore: 100,
    address: '1212 Magnolia Ct',
    city: 'Springfield',
    zip: '90210',
    birthday: '1960-01-25',
    allergies: false,
    emergencyContactName: 'Son',
    emergencyContactPhone: '555-1309',
    interestReason: 'Company.',
    positionPreferences: ['Cat Socialization'],
    availability: ['Weekday Mornings'],
    totalHours: 300,
    streak: 40,
    badges: ['Cat Whisperer', 'Silver Service', 'Reliable'],
  },
  {
    id: 't1-10',
    firstName: 'Michelle',
    lastName: 'Black',
    email: 'michelle.b@example.com',
    phone: '555-0310',
    status: 'active',
    role: 'Tier 1',
    joinDate: '2023-09-10',
    bio: 'Photographer by trade.',
    skills: ['Photography', 'Socialization'],
    reliabilityScore: 94,
    address: '1313 Palm St',
    city: 'Springfield',
    zip: '90210',
    birthday: '1988-10-08',
    allergies: false,
    emergencyContactName: 'Partner',
    emergencyContactPhone: '555-1310',
    interestReason: 'Taking photos of adoptable pets.',
    positionPreferences: ['Photography'],
    availability: ['Weekend Afternoon'],
    totalHours: 70,
    streak: 5,
    badges: ['Photographer', '50 Hours'],
  },
  {
    id: 't1-11',
    firstName: 'Nathan',
    lastName: '',
    email: 'nathan@example.com',
    phone: '555-0311',
    status: 'pending',
    role: 'Tier 1',
    joinDate: '2023-12-15',
    bio: 'Waiting for training session.',
    skills: [],
    reliabilityScore: 0,
    address: '1414 Sequoia Blvd',
    city: 'Springfield',
    zip: '90210',
    birthday: '2004-02-14',
    allergies: false,
    emergencyContactName: 'Dad',
    emergencyContactPhone: '555-1311',
    interestReason: 'College application.',
    positionPreferences: ['Feeding'],
    availability: ['Weekends'],
    totalHours: 0,
    streak: 0,
    badges: ['New Recruit'],
  },
  {
    id: 't1-12',
    firstName: 'Sonia',
    lastName: '',
    email: 'sonia@example.com',
    phone: '555-0312',
    status: 'active',
    role: 'Tier 1',
    joinDate: '2023-06-01',
    bio: 'Weekend regular.',
    skills: ['Dog Walking'],
    reliabilityScore: 91,
    address: '1515 Cypress Dr',
    city: 'Springfield',
    zip: '90210',
    birthday: '1995-07-07',
    allergies: false,
    emergencyContactName: 'Friend',
    emergencyContactPhone: '555-1312',
    interestReason: 'Exercise.',
    positionPreferences: ['Dog Walking'],
    availability: ['Saturday Morning'],
    totalHours: 65,
    streak: 4,
    badges: ['50 Hours', 'Weekend Warrior'],
  },
  {
    id: 't1-13',
    firstName: 'Violet',
    lastName: '',
    email: 'violet@example.com',
    phone: '555-0313',
    status: 'active',
    role: 'Tier 1',
    joinDate: '2023-11-01',
    bio: 'Loves the small dogs.',
    skills: ['Socialization'],
    reliabilityScore: 98,
    address: '1616 Redwood Ln',
    city: 'Springfield',
    zip: '90210',
    birthday: '2002-11-22',
    allergies: false,
    emergencyContactName: 'Mom',
    emergencyContactPhone: '555-1313',
    interestReason: 'Love dogs.',
    positionPreferences: ['Socialization'],
    availability: ['Sunday Afternoon'],
    totalHours: 20,
    streak: 8,
    badges: ['10 Hours', 'Rookie'],
  },

  // Teen
  {
    id: 'teen-1',
    firstName: 'Evi',
    lastName: '',
    email: 'evi@example.com',
    phone: '555-0401',
    status: 'active',
    role: 'Teen',
    joinDate: '2023-06-20',
    bio: 'High school junior.',
    skills: ['Cat Socialization'],
    reliabilityScore: 96,
    address: '1717 Poplar Pl',
    city: 'Springfield',
    zip: '90210',
    birthday: '2007-05-15',
    age: 16,
    allergies: false,
    emergencyContactName: 'Parent',
    emergencyContactPhone: '555-1401',
    interestReason: 'Community service hours.',
    positionPreferences: ['Cat Socialization'],
    availability: ['After School'],
    totalHours: 85,
    streak: 12,
    badges: ['Rising Star', '50 Hours'],
  },
  {
    id: 'teen-2',
    firstName: 'Josephine',
    lastName: 'Moraza',
    email: 'josephine.m@example.com',
    phone: '555-0402',
    status: 'active',
    role: 'Teen',
    joinDate: '2023-07-10',
    bio: 'Aspiring veterinarian.',
    skills: ['Cleaning', 'Observation'],
    reliabilityScore: 100,
    address: '1818 Fir St',
    city: 'Springfield',
    zip: '90210',
    birthday: '2006-09-09',
    age: 17,
    allergies: false,
    emergencyContactName: 'Parent',
    emergencyContactPhone: '555-1402',
    interestReason: 'Vet school prep.',
    positionPreferences: ['Cleaning'],
    availability: ['Weekends'],
    totalHours: 110,
    streak: 15,
    badges: ['Rising Star', 'Bronze Service', 'Reliable'],
  },
  {
    id: 'teen-3',
    firstName: 'Celina',
    lastName: '',
    email: 'celina@example.com',
    phone: '555-0403',
    status: 'active',
    role: 'Teen',
    joinDate: '2023-08-15',
    bio: 'Loves bunnies.',
    skills: ['Small Animal Care'],
    reliabilityScore: 94,
    address: '1919 Hemlock Dr',
    city: 'Springfield',
    zip: '90210',
    birthday: '2008-01-20',
    age: 16,
    allergies: true,
    emergencyContactName: 'Parent',
    emergencyContactPhone: '555-1403',
    interestReason: 'Bunnies are cute.',
    positionPreferences: ['Small Animals'],
    availability: ['Saturday Morning'],
    totalHours: 40,
    streak: 6,
    badges: ['Rising Star', 'Bunny Buddy'],
  },
  {
    id: 'teen-4',
    firstName: 'Kate',
    lastName: '',
    email: 'kate@example.com',
    phone: '555-0404',
    status: 'pending',
    role: 'Teen',
    joinDate: '2024-01-02',
    bio: 'Just applied.',
    skills: [],
    reliabilityScore: 0,
    address: '2020 Juniper Way',
    city: 'Springfield',
    zip: '90210',
    birthday: '2009-03-30',
    age: 14,
    allergies: false,
    emergencyContactName: 'Parent',
    emergencyContactPhone: '555-1404',
    interestReason: 'School club.',
    positionPreferences: ['Cats'],
    availability: ['Sunday'],
    totalHours: 0,
    streak: 0,
    badges: ['New Recruit'],
  },
  {
    id: 'teen-5',
    firstName: 'Qiuyao',
    lastName: '',
    email: 'qiuyao@example.com',
    phone: '555-0405',
    status: 'active',
    role: 'Teen',
    joinDate: '2023-05-20',
    bio: 'Very organized and helpful.',
    skills: ['Admin', 'Organization'],
    reliabilityScore: 98,
    address: '2121 Sycamore St',
    city: 'Springfield',
    zip: '90210',
    birthday: '2007-11-11',
    age: 16,
    allergies: false,
    emergencyContactName: 'Parent',
    emergencyContactPhone: '555-1405',
    interestReason: 'Experience.',
    positionPreferences: ['Admin'],
    availability: ['Thursday Afternoon'],
    totalHours: 75,
    streak: 9,
    badges: ['Rising Star', '50 Hours'],
  },
  {
    id: 'teen-6',
    firstName: 'Yana',
    lastName: '',
    email: 'yana@example.com',
    phone: '555-0406',
    status: 'active',
    role: 'Teen',
    joinDate: '2023-09-05',
    bio: 'Enthusiastic about dogs.',
    skills: ['Dog Walking'],
    reliabilityScore: 92,
    address: '2222 Alder Ave',
    city: 'Springfield',
    zip: '90210',
    birthday: '2006-12-25',
    age: 17,
    allergies: false,
    emergencyContactName: 'Parent',
    emergencyContactPhone: '555-1406',
    interestReason: 'Running with dogs.',
    positionPreferences: ['Dog Walking'],
    availability: ['Wednesday Afternoon'],
    totalHours: 50,
    streak: 4,
    badges: ['Rising Star', '50 Hours', 'Dog Walker'],
  },
  {
    id: 'teen-7',
    firstName: 'Mallory',
    lastName: '',
    email: 'mallory@example.com',
    phone: '555-0407',
    status: 'active',
    role: 'Teen',
    joinDate: '2023-10-15',
    bio: 'Creative and loves making toys for cats.',
    skills: ['Crafts', 'Cat Socialization'],
    reliabilityScore: 99,
    address: '2323 Beech Blvd',
    city: 'Springfield',
    zip: '90210',
    birthday: '2008-07-04',
    age: 15,
    allergies: false,
    emergencyContactName: 'Parent',
    emergencyContactPhone: '555-1407',
    interestReason: 'Making cats happy.',
    positionPreferences: ['Cat Socialization'],
    availability: ['Friday Evening'],
    totalHours: 35,
    streak: 7,
    badges: ['Rising Star', 'Cat Cuddler'],
  },
]

export const mockShifts: IShift[] = [
  // Linda's historical shifts for performance data
  {
    id: 's-t2-1-1',
    volunteerId: 't2-1',
    date: '2023-05-15',
    startTime: '09:00',
    endTime: '13:00',
    role: 'Dog Walking',
    status: 'all_good',
  },
  {
    id: 's-t2-1-2',
    volunteerId: 't2-1',
    date: '2023-08-20',
    startTime: '09:00',
    endTime: '13:00',
    role: 'Dog Walking',
    status: 'all_good',
  },
  {
    id: 's-t2-1-3',
    volunteerId: 't2-1',
    date: '2024-01-10',
    startTime: '09:00',
    endTime: '13:00',
    role: 'Dog Walking',
    status: 'all_good',
  },
  {
    id: 's-t2-1-4',
    volunteerId: 't2-1',
    date: '2024-01-17',
    startTime: '09:00',
    endTime: '13:00',
    role: 'Dog Walking',
    status: 'scheduled',
  },

  {
    id: 's1',
    volunteerId: 'v1',
    date: '2024-01-05',
    startTime: '08:00',
    endTime: '12:00',
    role: 'Morning Feeding',
    status: 'all_good',
  },
  {
    id: 's2',
    volunteerId: 'v1',
    date: '2024-01-12',
    startTime: '08:00',
    endTime: '12:00',
    role: 'Morning Feeding',
    status: 'scheduled',
  },
  // Mike's shifts
  {
    id: 's3',
    volunteerId: 'v2',
    date: '2024-01-06',
    startTime: '13:00',
    endTime: '17:00',
    role: 'Cat Socialization',
    status: 'all_good',
  },
  {
    id: 's4',
    volunteerId: 'v2',
    date: '2024-01-07',
    startTime: '13:00',
    endTime: '17:00',
    role: 'Cleaning',
    status: 'no_show',
    notes: 'Did not call.',
  },
]

export const mockIncidents: IIncident[] = [
  {
    id: 'i1',
    volunteerId: 'v2',
    date: '2024-01-07',
    severity: 'low',
    description: 'No-show for scheduled cleaning shift without prior notice.',
    recordedBy: 'Admin',
  },
]
export const availableBadges = [
  // Tenure & Milestones
  { id: 'b1', name: 'New Recruit', icon: '🌱', description: 'Completed your first shift!' },
  { id: 'b2', name: 'Rookie', icon: '⭐', description: 'Active for 1 month.' },
  { id: 'b3', name: 'Regular', icon: '🌟', description: 'Active for 6 months.' },
  { id: 'b4', name: 'Veteran', icon: '🎖️', description: 'Active for 1 year.' },
  { id: 'b5', name: 'Lifer', icon: '🏅', description: 'Active for 3 years.' },
  { id: 'b6', name: 'Legend', icon: '👑', description: 'Active for 5+ years.' },

  // Hours Club
  { id: 'h1', name: '10 Hours', icon: '🕙', description: 'Contributed 10 hours of service.' },
  { id: 'h2', name: '50 Hours', icon: '🕔', description: 'Contributed 50 hours of service.' },
  {
    id: 'h3',
    name: 'Bronze Service',
    icon: '🥉',
    description: 'Contributed 100 hours of service.',
  },
  {
    id: 'h4',
    name: 'Silver Service',
    icon: '🥈',
    description: 'Contributed 250 hours of service.',
  },
  { id: 'h5', name: 'Gold Service', icon: '🥇', description: 'Contributed 500 hours of service.' },
  {
    id: 'h6',
    name: 'Platinum Service',
    icon: '💎',
    description: 'Contributed 1000+ hours of service.',
  },

  // Canine Crew
  { id: 'd1', name: 'Dog Walker', icon: '🐕', description: 'Completed 10 Dog Walking shifts.' },
  { id: 'd2', name: 'Power Walker', icon: '👟', description: 'Completed 50 Dog Walking shifts.' },
  {
    id: 'd3',
    name: 'Leash Master',
    icon: '🦮',
    description: 'Handled a difficult dog successfully.',
  },
  { id: 'd4', name: 'Poop Scoop Pro', icon: '💩', description: 'The unsung hero of the yard.' },
  { id: 'd5', name: 'Puppy Pal', icon: '🐾', description: 'Helped with puppy socialization.' },
  { id: 'd6', name: 'Bark Ranger', icon: '🏞️', description: 'Took a dog on a field trip.' },

  // Feline Friends
  {
    id: 'c1',
    name: 'Cat Cuddler',
    icon: '🐱',
    description: 'Completed 10 Cat Socializing shifts.',
  },
  {
    id: 'c2',
    name: 'Cat Whisperer',
    icon: '🐈‍⬛',
    description: 'Completed 50 Cat Socializing shifts.',
  },
  { id: 'c3', name: 'Litter Box Hero', icon: '🧹', description: 'Cleaned the cat room 20 times.' },
  {
    id: 'c4',
    name: 'Laser Pointer Pro',
    icon: '🔴',
    description: 'Expert at feline entertainment.',
  },
  { id: 'c5', name: 'Kitty Comforter', icon: '🧶', description: 'Socialized shy cats.' },
  {
    id: 'c6',
    name: 'Meowtain Climber',
    icon: '🧗',
    description: 'Helped maximize vertical cat space.',
  },

  // Small Animals & Operations
  { id: 's1', name: 'Bunny Buddy', icon: '🐰', description: 'Cared for rabbits.' },
  { id: 's2', name: 'Pocket Pet Pal', icon: '🐹', description: 'Cared for hamsters/guinea pigs.' },
  { id: 'o1', name: 'Cleaning Crew', icon: '🧼', description: 'Completed 20 Cleaning shifts.' },
  { id: 'o2', name: 'Laundry Lord', icon: '🧺', description: 'Folded 100 loads of laundry.' },
  { id: 'o3', name: 'Dishwasher Dynamo', icon: '🍽️', description: 'Kept the bowls sparkling.' },
  {
    id: 'o4',
    name: 'Front Desk Ace',
    icon: '☎️',
    description: 'Managed the reception desk like a pro.',
  },

  // Special Shifts
  { id: 't1', name: 'Early Bird', icon: '🌅', description: 'Shift started before 9 AM.' },
  { id: 't2', name: 'Night Owl', icon: '🌙', description: 'Shift ended after 6 PM.' },
  { id: 't3', name: 'Weekend Warrior', icon: '📅', description: '10 weekend shifts completed.' },
  { id: 't4', name: 'Holiday Hero', icon: '🎄', description: 'Volunteered on a major holiday.' },
  { id: 't5', name: 'Double Header', icon: '✌️', description: 'Completed 2 shifts in one day.' },
  {
    id: 't6',
    name: 'Last Minute Savior',
    icon: '🚑',
    description: 'Picked up a shift with < 24h notice.',
  },

  // Reliability & Attributes
  { id: 'r1', name: 'Reliable', icon: '🛡️', description: '100% attendance for 3 months.' },
  { id: 'r2', name: 'Perfect Year', icon: '📅', description: '100% attendance for 12 months.' },
  { id: 'r3', name: 'Mentor', icon: '🎓', description: 'Trained a new volunteer.' },
  { id: 'r4', name: 'Photographer', icon: '📸', description: 'Took adoption photos for pets.' },
  {
    id: 'r5',
    name: 'Matchmaker',
    icon: '💘',
    description: 'Helped a pet find their forever home!',
  },
  { id: 'r6', name: 'Shelter Guardian', icon: '👼', description: 'Donated supplies or funds.' },

  // Fun & Misc
  {
    id: 'f1',
    name: 'The Treat Dispenser',
    icon: '🍪',
    description: 'Dogs know you have the goods.',
  },
  {
    id: 'f2',
    name: 'Patient Saint',
    icon: '🧘',
    description: 'Spent >1 hour with a single shy animal.',
  },
  {
    id: 'f3',
    name: 'Rising Star',
    icon: '🚀',
    description: 'Completed first 20 hours of volunteering.',
  },
  { id: 'f4', name: 'Event Star', icon: '🎪', description: 'Helped at an adoption event.' },
  {
    id: 'f5',
    name: 'Transport Team',
    icon: '🚗',
    description: 'Drove an animal to the vet/rescue.',
  },
]
